name: Python CI

# Run this workflow every time a new commit is pushed to repository
on: [pull_request]

jobs:
  run-unit-tests:
    
    name: Run all unit tests in codebase
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.0

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Test with pytest
      run: |
        sed -i '12s/.*/MSEG_DST_DIR="\/dummy\/path"/' mseg/utils/dataset_config.py
        pip install -e .
        pip install pytest
        pytest tests/
